#+TITLE: My Emacs configuration

This is my personal =~/.emacs.d= directory, settings are mostly stolen from all over the internets and adapted for my taste and needs. Feel free to do the same or just lookup and borrow the parts you're after. If you learned something here, my goal is reached.

After watching [[http://cestlaz.github.io/stories/emacs/][Mike Zamansky's webcasts]] I have decided to declare .emacs.d bancruptcy and start again.


* Installation

While I'm certain most things will work on any modern Emacs, personally I am currently using GNU Emacs 24.5.1 on macOS, and, therefore, can only guarantee the configuration to work correctly on a comparable setup.

On macOS you can install Emacs using Homebrew, I recommend =emacs-plus=:

#+BEGIN_SRC shell
brew tap d12frosted/emacs-plus
brew install emacs-plus --without-spacemacs-icon --HEAD
brew linkapps emacs-plus
#+END_SRC

Before installing this configuration ensure you don't have =~/.emacs.d= directory. If you do, then either move it or dispose of it before proceeding further.

To download this configuration as you new =~/.emacs.d=:

#+BEGIN_SRC shell
git clone https://github.com/timanin/emacs.d.git ~/.emacs.d
#+END_SRC

You'll also need the [[https://github.com/tonsky/FiraCode][Fira Code]] font, so either get it from their github page or install using Homebrew:

#+BEGIN_SRC shell
brew tap caskroom/fonts
brew cask install font-fira-code
#+END_SRC


* Usage

List of features:

- [ ] Styled to work great on macOS.
- [ ] Modular design thanks to the [[https://github.com/jwiegley/use-package][use-package]] macro.
- [ ] [[http://orgmode.org][Org-mode]] improvements ([[https://mobileorg.github.io][MobileOrg]]?).
- [ ] Deferred module loading for fast startup.
- [ ] Intended to be run constantly in server mode.
- [ ] Code completion with [[http://company-mode.github.io][company-mode]].
- [ ] ligatures support (Fira Code)
- [ ] base16-theme
- [ ] smart modeline
- [ ] all-the-icons
- [ ] [[https://magit.vc][Magit]] with =C-x g=
- [ ] Syntax checking with [[http://www.flycheck.org/][flycheck]].
- [ ] which-key
- [ ] projectile
- [ ] Snippets with [[http://joaotavora.github.io/yasnippet/][yasnippet]].
- [ ] persistent scratch
- [ ] window switching using ace-window
- [ ] ibuffer
- [ ] expand-region with =C-==

Supported languages/frameworks:

- [ ] Ansible
- [ ] Elisp
- [ ] Fish
- [ ] Groovy
- [ ] Haskell
- [ ] JSON
- [ ] Markdown
- [ ] Python
- [ ] Terraform
- [ ] Web
- [ ] YAML


* Licence

Copyright (C) 2016  Sergey Timanin

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

