#+TITLE: My Emacs configuration

This is my .emacs.d directory, settings are mostly stolen from all over the internets and adapted for my taste and needs. Feel free to do the same or just lookup and borrow the parts you're after. If you learned something here, my goal is achieved.

* Installation

While I'm certain most things will work on any modern Emacs, personally I am currently using GNU Emacs 24.5.1 on macOS, and, therefore, can only guarantee the configuration to work correctly on a comparable setup.

On macOS you can install Emacs using =brew=:

#+BEGIN_SRC shell
brew install emacs --with-cocoa
#+END_SRC

Before installing this configuration ensure you don't have =~/.emacs.d= directory. If you do, then either move it or dispose of it before proceeding further.

To download this configuration as you new =~/.emacs.d=:

#+BEGIN_SRC shell
git clone https://github.com/timanin/emacs.d.git ~/.emacs.d
#+END_SRC

* Usage

List of features pending.

* Licence

Copyright (C) 2016  Sergey Timanin

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

